version: "3.0"
services:
    api:
        build: .
        ports:
            - "9000:9000"
        depends_on: 
            - db
    db:
        image: mongo
        ports:
            - "27017:27017"